### ISSUE TITLE
Can't log in to spotify

### ISSUE THREAD

**Issue by AlexEshoo** [plamere/spotipy#105]
So maybe I'm missing something here, but when I run the example program and it gives me a link to visit, I get to a log in screen, but when I try to click log in, nothing happens. I can click the log in through facebook link and this logs me in but when I paste it as the redirected link in spotipy, it raises an exception:

```
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request

```

Am I doing something wrong? I have my credentials set as environment variables and I'm using http://example.com/callback/ as my redirect uri

**Comment by AlexEshoo** [comment]
I found out that its actually logging me in, but not redirecting anywhere. If I put in a bad password it tells me such. but when I put my real password in and click log in, not a thing happens. If I open up the web player in another tab I'm logged in.

**Comment by AntonioSerrano** [comment]
The same happens to me. Unlike you, if I open the web player in another tab I am not logged in. If I try to enter the redirect URI set for my application from https://developer.spotify.com/my-applications/, I get the same Bad Request. Any idea?

**Comment by AntonioSerrano** [comment]
OK. I solved the problem, at least partially. I specified the redirect URI in line 13 of the example program:

`token = util.prompt_for_user_token(username, scope, redirect_uri = 'https://www.google.com')`

Theoretically, it was not necessary because I already did it when setting the environment variables. Anyway, now I can log in. Hooray. But don't count the chickens yet. When entering the URL (my original redirect URI plus a bunch of letters/numbers), I got another bad request, for a change:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spotipy/util.py", line 86, in prompt_for_user_token
token_info = sp_oauth.get_access_token(code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spotipy/oauth2.py", line 217, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

It seems that the origin of the problem is in the script 'oauth2.py' (line 217) within the Spotipy library. You can take a look at that script [here](https://github.com/plamere/spotipy/blob/master/spotipy/oauth2.py). And you can do same with [utils.py](https://github.com/plamere/spotipy/blob/master/spotipy/util.py). Unfortunately, these scripts are beyond my grasp. Any clue? Thanks.

**Comment by AntonioSerrano** [comment]
Solved it. In order to run the [Authorization Code Flow example code](https://spotipy.readthedocs.io/en/latest/#authorization-code-flow) provided in the Spotipy's documentation correctly, I specified the redirect URI in line 13 of the example script when calling util.prompt_for_user_token, even when I have done this previously when setting environment variables:

`token = util.prompt_for_user_token(username, scope, redirect_uri = 'https://example.com/callback/')`

Likewise, do not use https://www.google.com or similar web address as your redirect URI. Instead, try 'https://example.com/callback/' or 'http://localhost/' as suggested [here](https://spotipy.readthedocs.io/en/latest/#authorized-requests). Do not forget that the redirected URL once you are logged in must have the word **code** included.

Cheers,
Antonio

**Comment by AlexEshoo** [comment]
I've tried what you said, but when I use any of the redirect URIs you suggest the webpage I am brought to has the following message: "INVALID_CLIENT: Invalid redirect URI"
Needless to say, when I past the redirected url in the terminal window I get the same traceback as before.

**Comment by nplevitt** [comment]
Hey @AlexEshoo, I don't know if you ever figured this out, but I just solved the same problem.

I found that you have to add your redirect URI that you either include in your bash profile or specify directly in the token prompt to your list of redirect URIs directly in the settings for your Spotify Dev App.

**Comment by mmako1** [comment]
@nplevitt So I have specified it within my bash , Spotify Dev App, and within my python file. I still get the invalid error, is it due to the fact that I'm using 'https://example.com/callback/' as my redirect uri?

**Comment by mtbsickrider** [comment]
@AlexEshoo @mmako1 

Have you guys been able to figure it out? Below is my code from the examples and i get INVALID_CLIENT: Invalid redirect URI

`token = util.prompt_for_user_token(username,
                                   scope,
                                   client_id=defintions.SPOTIPY_CLIENT_ID,
                                   client_secret=defintions.SPOTIPY_CLIENT_SECRET,
                                   redirect_uri=defintions.SPOTIPY_REDIRECT_URI)`

**Comment by mtbsickrider** [comment]
nevermind :) Had to whitelist it from spotify dashboard!
