### ISSUE TITLE
user playlist doesn't return Discover Weekly

### ISSUE THREAD

**Issue by nyboer** [plamere/spotipy#133]
I noticed that user playlists doesn't include the user's Discover Weekly as one of the items. I found through Spotify's test site that if you can query "me", you can get the Discover Weekly as a result. 
That is
https://api.spotify.com/v1/users/{user_id}/playlists
doesn't return Discover Weekly, but
https://api.spotify.com/v1/me/playlists
Unless I'm mistaken, there's no way to call the latter through spotipy, correct?

**Comment by cmcnutt1** [comment]
I'm a little late to the party, but I've had this same problem before. So the problem with Discover Weekly playlists is that they're technically listed under the user 'spotify', rather than being directly tied to your account. To fix this, I added some lines to the client.py file under the spotipy/ directory which allow you to get information from public playlists (e.g. any playlist that isn't owned directly by you). I've submitted the change in a pull request  (#156) so that it will be a built in feature.

**Comment by cmcnutt1** [comment]
I stumbled upon a different way to access the discover playlist, without the pull request that I mentioned in my last response. If you go to the spotify web player, you can right click on the discover list and click "Make Public", and then it should show up when you call current_user_playlists(). 

I'm not really sure why this works, but it started showing up for me once I made it public

**Comment by plamere** [comment]
not a spotipy issue per se
