### ISSUE TITLE
How can I cite spotipy?

### ISSUE THREAD

**Issue by EmanuelFontelles** [plamere/spotipy#473]

**Comment by stephanebruckert** [comment]
According to https://guides.github.com/activities/citable-code/ we could ask the repo owner to add spotipy to https://zenodo.org/. If you need this soon you should try tweeting @plamere to request this.

Otherwise, you can still have a look at how people usually cite public github repositories https://academia.stackexchange.com/q/14010/24150, it could look like:

> Paul Lamere, Spotipy, (2020), A light weight Python library for the Spotify Web API, https://github.com/plamere/spotipy

**Comment by stephanebruckert** [comment]
Closing in favor of solution in https://academia.stackexchange.com/q/14010/24150
