### ISSUE TITLE
Album release date

### ISSUE THREAD

**Issue by cmplctdsmplcty** [plamere/spotipy#53]
Currently, "artist_albums()" doesn't return the album's release date. The release_date can only be found when calling "album()" or "albums()".

Can we bring this "release_date" field into the artist_albums return data?

**Comment by joohoi** [comment]
This is due to the Spotify API response values, to merge the release_date to artist_albums() would require spotipy to make two requests to the web backend, and in this case it wouldn't be any different from the user to make those requests themselves.

See return values of:

https://developer.spotify.com/web-api/get-artists-albums/
vs.
https://developer.spotify.com/web-api/get-album/

**Comment by stephanebruckert** [comment]
This should work now, I can now see the `release_date` as part of the `artist_albums()` response https://developer.spotify.com/console/get-artist-albums/
