### ISSUE TITLE
Avoid duplicate tracks on a playlist

### ISSUE THREAD

**Issue by AlexandreAguido** [plamere/spotipy#601]
This is an awesome project, it saved me hours on coverting a radio history to a playlist,
but I did not find a way to avoid adding duplicate tracks to a playlist. I think that a native option to avoid duplicate
tracks on a playlist would be nice

**Comment by stephanebruckert** [comment]
I agree, ideally the API would allow this https://github.com/spotify/web-api/issues/118, but it's closed as wont-fix.

The current recommended practice is that each app keeps tracks of the current tracks in a playlist, and check whether it's already there before inserting.

Unfortunately, it could be hard to do this in the library, because we don't know in advance how to persist the current playlist tracks (what DB? what structure?). The next option would be to retrieve the full playlist every time we call `add_track_to_playlist()`, but that could be misused and lead to poor performance (a playlist can have up to 11k tracks).

I'm going to keep this open for a bit in case someone can suggest a good solution, otherwise we will likely close it. Also keeping in mind that spotipy is "light weight".

**Comment by Peter-Schorn** [comment]
One suggestion I have is to cache the `snapshot_id` of a playlist, which changes each time the playlist changes. Think of it as like a hash code. This prevents you from having to retrieve all of the tracks in a playlist to see if it has changed. See https://developer.spotify.com/documentation/general/guides/working-with-playlists/#version-control-and-snapshots

You can use the following to retrieve just the snapshot id of a playlist:
```python
snapshot_id = spotify.playlist("37i9dQZF1DXdLtD0qszB1w", fields="snapshot_id")["snapshot_id"]
```

**Comment by stephanebruckert** [comment]
@Peter-Schorn isn't the `snapshot_id` changing even when a duplicate is added?

**Comment by Peter-Schorn** [comment]
> @Peter-Schorn isn't the `snapshot_id` changing even when a duplicate is added?

Yes, it will change even if a duplicate is added. And, even if you add a track and then remove that same track, the snapshot id will *still* change. However, if the user hasn't modified the playlist at all, then parameter can still be useful for avoiding retrieving all of the tracks again.

**Comment by AlexandreAguido** [comment]
Well I opened this issue because I thought that the spotify api could easily handle the option to add or avoid duplicate songs, but sadly they don't support it.

A way to manage it without depending of spotify api would be to keep track of the ids for each track in the playlist and the snapshot_id then check if the snapshot_id changed before downloading the playlist info and finally check with tracks don't belong to a playlist before insert them.  But for a web app with hundreds of users that depends of this project it will increase significantly the resouce usage (space, bandwith, and CPU resource for the search operations) breaking the purpose of this project to be a "lightweight" 

I say leave it as it is and hope that something like this https://github.com/spotify/web-api/issues/444 be implemented quickly.

**Comment by stephanebruckert** [comment]
yep... closing then. Thanks for reporting though, I share the idea.
