### ISSUE TITLE
Can't search for artist and year at the same time

### ISSUE THREAD

**Issue by Zacharias3D** [plamere/spotipy#768]
Hi everyone,

I am trying to use the `search`-function to query for a specific song from a specific year.
To accomplish this I call the `search`-function with `q=track:Chattanooga Choo Choo+year:1939`. This works just fine when trying the request in postman, but when executing it in Python I do not get any results.

When I debugged, I realized that in the `_encode_params()`-function of the models-module in requests-lib, my query string is encoded which leads to the replacement of the joining "+" in my query-string ("+" becomes "%2B"). It seems though, that the Spotify API needs a "+" and not a URI-encoded "+".
When trying the query-string `track:Chattanooga%20Choo%20Choo%2Byear:1939` in postman I also got no results. Replacing "%2B" with "+" showed me results again.

Any advice? I probably just oversee some simple issue.

Greetings,
Zacharias

**Comment by Peter-Schorn** [comment]
A literal `+` character must be percent-encoded to `%2B`, otherwise is the percent-encoded form of the space character. (A space character can also be percent-encoded as `%20`).

When you make the request in Postman, it assumes that the `+` is already the percent-encoded form of the space character. Therefore, the decoded form of the `q` query parameter value in the Postman request is `track:Chattanooga Choo Choo year:1939`. This is what you're searching for in Postman.

spotipy, on the other hand, will percent encode the query, even if it is already percent-encoded. Therefore, it will percent-encode the `+` character to `%2B`. There is no track named "Chattanooga Choo Choo+", so you get no results.

**Comment by Zacharias3D** [comment]
Oh my god..

Thanks so much. Who would have thought that a "+" too much would cost me hours of my day.

Thanks a lot!!!
